name: 03 - Schedule
on:
    schedule:
      - cron: '15 17 * * *'
jobs:
  schedule:
    runs-on: ubuntu-24.04
    steps:
        - name: Saludar
          run: echo "Hola desde GitHub Actions - Ejecución programada"