name: 03 - Schedule
on:
    schedule:
      - cron: '45 16 * * *' # Ejecutar todos los días a medianoche
jobs:
  schedule:
    runs-on: ubuntu-24.04
    steps:
        - name: Saludar
          run: echo "Hola desde GitHub Actions - Ejecución programada"